GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJBcHJpbGlhIFJhaG1hIEt1c3VtYXN0dXRpIiwiYXMiOiJhZG1pbi0xIiwiZW1haWwiOiJhcHJpbEBtYWlsLmNvbSIsImlhdCI6MTYzNzA0MjU3NCwiZXhwIjoxNjM3MDQyNTk0fQ.YXiFXBM2lIj0sh9MGHsbJOYcRwWwdfXNgdpcUmwlHfI

###
POST http://localhost:5000/register
Content-Type: application/json

# {
#     "name": "Hanif Faiz Hidayat",
#     "as": "resepsionis-1",
#     "email": "hanif@mail.com",
#     "password": "1234",
#     "confPassword": "1234"
# }
{
    "name": "Aprilia Rahma Kusumastuti",
    "as": "admin-1",
    "email": "april@mail.com",
    "password": "1234",
    "confPassword": "1234"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "april@mail.com",
    "password": "1234"
}

###
POST http://192.168.1.3:5000/contacts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBcHJpbGlhIFJhaG1hIEt1c3VtYXN0dXRpIiwiYXMiOiJhZG1pbi0xIiwiZW1haWwiOiJhcHJpbEBtYWlsLmNvbSIsImlhdCI6MTYzODUyOTkxNSwiZXhwIjoxNjM4NTMzNTE1fQ.YBwVIYfaPeNocCfPS-DLhupuAy8NAzUCgb_Yz5dggDI

{
    "name": "Tes 123 456",
    "gender": "F",
    "phone": "08000000000",
    "email": "abc.xyz@mail.com",
    "organization": "FRI",
    "address": "JL. T. Ismail XVII No. 3 Sekeloa",
    "city": "Jakarta"
}

###
POST http://localhost:5000/tickets
Content-Type: application/json

{
    "contactId": "37",
    "relationshipCode": "FAMF"
}

###
POST http://localhost:5000/messages
Content-Type: application/json

{
    "contactId": "4",
    "message": "Selamat, semoga samawa"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
POST http://localhost:5000/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBcHJpbGlhIFJhaG1hIEt1c3VtYXN0dXRpIiwiYXMiOiJhZG1pbi0xIiwiZW1haWwiOiJhcHJpbEBtYWlsLmNvbSIsImlhdCI6MTYzODM4ODI5OSwiZXhwIjoxNjM4MzkxODk5fQ.IYJFgnKLOM5e0AUZw3izp6n19bCgztAskBDRpU9iJNU